# Generated by Django 4.2.8 on 2023-12-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="cover_image",
            field=models.TextField(default="static/images/no_cover_image.png"),
        ),
    ]
