# Generated by Django 4.2.8 on 2023-12-15 00:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_make_genre_many_to_many"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="last_edited",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name="media", unique_together={("title", "release_date")},
        ),
    ]
