# Generated by Django 4.2.8 on 2023-12-18 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_changed_datetimefield_in_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="cast",
            name="birthdate",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
