# Generated by Django 4.2.8 on 2023-12-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_add_birthdate_to_cast"),
    ]

    operations = [
        migrations.AddField(
            model_name="buddiesinvite",
            name="responded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupinvite",
            name="responded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="partyinvite",
            name="responded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
